######################################################################
# Automatically generated by qmake (3.0) ?? 5? 30 11:50:24 2013
######################################################################

TEMPLATE = app
TARGET = sckchess
INCLUDEPATH += .
QT += widgets
CONFIG += c++11

# Input
HEADERS += board.h main_window.h piece.h \
    engine.h
SOURCES += board.cc main.cc main_window.cc piece.cc \
    engine.cc
RESOURCES += images.qrc
